### ISSUE TITLE
Crash on creating new scene after selecting an object in the inspector

### ISSUE THREAD

**Issue by richardjdare** [kaveh808/kons-9#119]
branch: text-engine, 
Windows 10, SBCL 2.2.7

The app crashed at the start of Demo 4 (demo-ui.lisp) when I triggered "New Scene"
```
An unhandled error condition has been signalled:
   OpenGL signalled (1282 . INVALID-OPERATION) from END.


Backtrace for: #<SB-THREAD:THREAD "main thread" RUNNING {1001F98143}>
0: ((FLET "CLEANUP-FUN-10" :IN SB-IMPL::REFILL-INPUT-BUFFER)) [cleanup]
1: (SB-IMPL::REFILL-INPUT-BUFFER #<SB-SYS:FD-STREAM for "standard input" {100536A033}>)
2: (SB-IMPL::INPUT-CHAR/UTF-8 #<SB-SYS:FD-STREAM for "standard input" {100536A033}> NIL 0)
3: ((LAMBDA (&REST REST) :IN SB-IMPL::GET-EXTERNAL-FORMAT) #<SB-SYS:FD-STREAM for "standard input" {100536A033}> NIL 0)
4: (READ-CHAR #<SB-SYS:FD-STREAM for "standard input" {100536A033}> NIL 0 #<unused argument>)
5: (READ-CHAR #<SYNONYM-STREAM :SYMBOL SB-SYS:*STDIN* {1000092143}> NIL 0 #<unused argument>)
6: (SB-IMPL::%READ-PRESERVING-WHITESPACE #<SYNONYM-STREAM :SYMBOL SB-SYS:*STDIN* {1000092143}> NIL (NIL) T)
7: (SB-IMPL::%READ-PRESERVING-WHITESPACE #<SYNONYM-STREAM :SYMBOL SB-SYS:*STDIN* {1000092143}> NIL (NIL) NIL)
8: (READ #<SYNONYM-STREAM :SYMBOL SB-SYS:*STDIN* {1000092143}> NIL (NIL) NIL)
9: (SB-IMPL::REPL-READ-FORM-FUN #<SYNONYM-STREAM :SYMBOL SB-SYS:*STDIN* {1000092143}> #<unused argument>)
10: (SB-IMPL::REPL-FUN NIL)
11: ((LAMBDA NIL :IN SB-IMPL::TOPLEVEL-REPL))
12: (SB-IMPL::%WITH-REBOUND-IO-SYNTAX #<FUNCTION (LAMBDA NIL :IN SB-IMPL::TOPLEVEL-REPL) {1003F1720B}>)
13: (SB-IMPL::TOPLEVEL-REPL NIL)
14: (SB-IMPL::TOPLEVEL-INIT)
15: ((FLET SB-UNIX::BODY :IN SB-IMPL::START-LISP))
16: ((FLET "WITHOUT-INTERRUPTS-BODY-3" :IN SB-IMPL::START-LISP))
17: (SB-IMPL::%START-LISP)
18: ("foreign function: #x140035AE5")
19: ("foreign function: #x1400053C0")
```

The crash seems to occur when you create a new scene after selecting an object in the inspector
Steps to recreate:

Tab to open the menu
C C C (create circle shape)
Tab I S (open shape inspector)
Select shape in the inspector
hit ESC to close the inspector
Tab to hide the menu

Tab to open the menu
S N (new scene)

It won't crash if you deselect the shape before closing the inspector.

(I was unable to recreate the bug on my xubuntu virtual machine because text-engine crashes straight away with an opengl error. It may be a Virtual Box problem, I need to investigate)

**Comment by kaveh808** [comment]
Thanks for testing. I will look into this. I suspect I need to close all inspectors on a New Scene, as they don't update properly.

**Comment by kaveh808** [comment]
Disabled show/hide of group nodes in Shape and Motion inspectors for now. All nodes are shown (expanded) so that updating inspectors works when scene is edited via GUI.
