### ISSUE TITLE
Ctrl, Alt or Shift will also show the main menu if it is not visible.

### ISSUE THREAD

**Issue by richardjdare** [kaveh808/kons-9#120]
Windows 10, SBCL 2.2.7 Branch: text-engine

Steps to reproduce:
Start kons-9
hit TAB to hide the main menu
hit ctrl, alt or shift
The menu comes back up.

**Comment by kaveh808** [comment]
Thanks. Will look into this.

One undocumented feature is that the keyboard bindings for the main menu are active even if the menu is hidden. So you can press 'C' and get the "Create" menu, etc.

**Comment by kaveh808** [comment]
The bug was a side effect of the undocumented feature.
