### ISSUE TITLE
stable kons-9 commit

### ISSUE THREAD

**Issue by awolven** [kaveh808/kons-9#169]
What is the most recent stable kons-9 commit, where everything was testing fine?

**Comment by kaveh808** [comment]
The current main branch.

**Comment by awolven** [comment]
How do you run the demos?

**Comment by awolven** [comment]
The function kons-9::p+ is undefined.

**Comment by awolven** [comment]
The whole "point" system seems to have been ripped out of the latest
commits for a few days and none of the demos actually work.

**Comment by kaveh808** [comment]
The demos work on my machine, and I pushed to main on Friday.

We're using `point-origin.lisp` so it's `p:+` now. But I just checked and `p+` also works.

To run the demos:
`(in-package :kons-9)`
`(run)`
Then eval the demos.

I'll run some tests in the morning.

**Comment by awolven** [comment]
(find-package :p)
--> nil

grep -r point-origin
kons-9.asd:   (:file "src/kernel/point-origin")

There is no p+ definition in src/kernel/point-origin.lisp

**Comment by awolven** [comment]
(defun p+ (a b) (p! (+ (p:x a) (p:x b)) (+ (p:y a) (p:y b)) (+ (p:z a) (p:z
b))))

eval:
(with-clear-scene
  (add-shape *scene* (make-cut-cube 2.0)))

The function kons-9::p/ is undefined.

something got ripped out

**Comment by foretspaisibles** [comment]
That's a good candidate for the next thing to add to the test suite. :-) I can pick up but maybe you are interested in that topic @awolven ?

**Comment by awolven** [comment]
Yes, I'm interested in expanding the test suite, if that is what you're
asking.

**Comment by lukego** [comment]
@awolven The snippet you posted works fine for me on Linux with commit 308b1215b9fb964d55be528511e68d84e6de2c03 i.e. current tip of the main branch. I wonder what is different on your machine? (Is it a platform-related issue?)

Result:

![Screenshot from 2022-11-07 14-37-00](https://user-images.githubusercontent.com/13791/200324252-c220dc0d-8c2d-4e38-8933-6fb8676b47b7.png)

**Comment by awolven** [comment]
on windows:

cd ~/AppData/local
find . -name \*.fasl -delete

;; make your computer as fresh as a new user would have it on the first
download of kons-9
 you should also be able to reproduce this if you do:
(ql:update-dist "quicklisp")

**Comment by awolven** [comment]
I have gone about as far as I can with this vulkan port until I get kons-9
polygons working.

**Comment by kaveh808** [comment]
Tagging @JMC-design who did the point-origin port, in case he has any ideas of what may be going on.

**Comment by awolven** [comment]
Can you at least replicate it?

**Comment by JMC-design** [comment]
I'm on  a new machine. I just cloned the repo and ran it. Everything seems to be fine. origin is in depends, the nickname is there and the demos work.
This seems to be an old file @awolven is looking at.

**Comment by foretspaisibles** [comment]
> Yes, I'm interested in expanding the test suite, if that is what you're asking.
> […](#)

Yes, there is and introductory discussion in #112, you can skim towards the end to find the interesting bits. I'm also happy to answer questions and provide any help. We could also pair some time over zoom if you're interested, I believe it's a great way to quickly get started!

**Comment by awolven** [comment]
Ok, these are the steps I am taking:

cd ~/AppData/Local
find . -name \*.fasl -delete

git clone ***@***.***:awolven/kons-9.git kons-9-test

I edit my .sbclrc to only point to ~/kons-9-test/ not ~/kons-9/

I start lisp:

(ql:update-client)

(ql:update-dist "quicklisp")

(ql:quickload :kons-9)

(kons-9::run)

I open the file :

~/kons-9-test/test/demo-kernel.lisp

I cut and paste this form into the repl:

(with-clear-scene
  (add-shape *scene* (make-cut-cube 2.0)))

I get:
The function kons-9::p+ is undefined.

I cd to ~/kons-9-test/
 grep -r "p+"

There is no definition of p+ that isn't commented out.
And the commented out definition doesn't work.

Apparently quicklisp is not providing a definition of p+ either.

Can I please get the source code to p+ and brethren?

I can try it on Linux and Mac if you really want me to, but I am telling
you, there is a problem, at least on Windows.

**Comment by awolven** [comment]
shit, i found a typo

**Comment by awolven** [comment]
Ok I repeated the test with:

rm -rf ~/kons-9-test/
git clone ***@***.***:kaveh808/kons-9.git kons-9-test

I get the same issue.

There is no definition of p+ in kons-9-test which I cloned directly from
Kaveh's repo.

**Comment by kaveh808** [comment]
p+ is defined in point-origin:

```
(defmacro def-point-func-1 (op)
  `(defun ,(concat-syms 'p op) (p val)
     (ctypecase val
       (p:vec (,(find-symbol (symbol-name op) 'p) p val))
       (number (p! (,op (p:x p) val)
                   (,op (p:y p) val)
                   (,op (p:z p) val))))))

(def-point-func-1 +)
(def-point-func-1 -)
(def-point-func-1 *)
(def-point-func-1 /)
```

**Comment by kaveh808** [comment]
@mikelevins Are you having any trouble running on Windows?

**Comment by awolven** [comment]
;; here's the macroexpansion:

(defun |p+| (p val)
  (ctypecase val
    (p:vec (p:+ p val))
    (number (p! (+ (p:x p) val) (+ (p:y p) val) (+ (p:z p) val)))))

This is brittle code.  Here's what the macro should be:

(defmacro def-point-func-1 (op)
  `(defun ,(intern (concatenate 'string "P" (symbol-name op))) (p val)
     (ctypecase val
       (p:vec (,(find-symbol (symbol-name op) 'p) p val))
       (number (p! (,op (p:x p) val)
                   (,op (p:y p) val)
                   (,op (p:z p) val))))))

**Comment by kaveh808** [comment]
Thanks for catching this Andrew.

I can make this change in my next merge with main, unless you prefer making an issue and a pull request?

**Comment by awolven** [comment]
Go ahead and make the change and merge it.  What we should do is run the
tests with *print-case* and *read-case* set to alternate settings.  I was
going to make an issue (when the time was right, I guess now...) with
*read-default-float-format* set to double-float and (pushnew
:3d-vectors-double-floats *features*) which are much bigger problems that
need testing/fixes.  Those are important to the scientific/engineering
community which I am a part of.

**Comment by awolven** [comment]
Oh yeah, and there is also the case that in computer-aided design, Z is UP,
while in the content creation community Y is UP that I should go ahead and
mention.
