### ISSUE TITLE
add find-closest-point method

### ISSUE THREAD

**Issue by kaveh808** [kaveh808/kons-9#17]
Implement a method `find-closest-point` for the class `polyhedron`. Ignore the shape's transform.

The returned point must be on the surface of a face, on an edge, or at a vertex or the polyhedron.

**Comment by kaveh808** [comment]
@foretspaisibles Would you be interested in tackling this issue? You seem to be mathematically inclined. :)

**Comment by foretspaisibles** [comment]
@kaveh808 Ah ah yes, I actually paid some thoughts to it and try to figure out how to find the closest points on two disjoint polyhedrons. Need to experiment a bit with this!

**Comment by kaveh808** [comment]
Cool. I am actually looking for a point to a polyhedron, not two polyhedra. If necessary, you can make the simplifying assumption that  the polyhedron only has convex faces, or even is triangulated.
