### ISSUE TITLE
`(run)` does not dispatch a new thread

### ISSUE THREAD

**Issue by SeungheonOh** [kaveh808/kons-9#246]
When I execute `(run)`, the main thread(REPL) gets locked with execution of `(run)` and so I'm unable to run any other commands. I'm not sure if this intended design, but I can't follow the guide written in demos and README. Some guidance would be really helpful.

**Comment by kaveh808** [comment]
What platform are you running on? I'm on MacOS, but maybe someone can help for other platforms.

**Comment by SeungheonOh** [comment]
I'm running it on Nixos, x86_64-linux.

**Comment by kaveh808** [comment]
Perhaps someone on Linux could suggest a reason for this?

**Comment by SeungheonOh** [comment]
I setup SLIME in my emacs setup, and was able to run `(run)` without it blocking the thread. I'm not 100% sure if that was the issue, but now I can draw things!
