### ISSUE TITLE
Problem running kons-9

### ISSUE THREAD

**Issue by stew-j** [kaveh808/kons-9#4]
The problem is most likely because this system is so ancient, but FYI I was unsuccessful trying to run kons-9 on my only remaining Apple H/W:

Mac OS X 10.6.8
CCL 1.3

ASDF could not load kons-9 because Objective-C runtime exception: 
-[NSCachedWhiteColor CGColor]: unrecognized selector sent to instance 0x146120.
> Error: Objective-C runtime exception: 
>        -[NSCachedWhiteColor CGColor]: unrecognized selector sent to instance 0x146120
> While executing: CCL::CHECK-NS-EXCEPTION, in process Listener(4).

**Comment by mdbergmann** [comment]
I'm not entirely sure. But there were CCL versions partially specific to Mac OS X versions.
You could probably run CCL 1.7, or 1.8:
https://ccl.clozure.com/download-1.7.html

Maybe that would help with the ObjC runtime error.

**Comment by stew-j** [comment]
Thanks! I wasn't sure which version would still run on the old Mini.  I'll give those two a try.

**Comment by stew-j** [comment]
Of course, "the devil is in the details":

https://ccl.clozure.com/download-1.7.html

> The preferred way to get Clozure CL is via *Subversion*. For example, to get Clozure CL 1.7 for Darwin/x86, you'd type (where the $ is the shell prompt): 

    $ svn co http://svn.clozure.com/publicsvn/openmcl/release/1.7/darwinx86/ccl
    Redirecting to URL 'https://svn.clozure.com/publicsvn/openmcl/release/1.7/darwinx86/ccl':
    svn: E170013: Unable to connect to a repository at URL 'https://svn.clozure.com/publicsvn/openmcl/release/1.7/darwinx86/ccl'
    svn: E175003: The server at 'https://svn.clozure.com/publicsvn/openmcl/release/1.7/darwinx86/ccl' does not support the HTTP/DAV protocol
   
    $ ftp ftp.clozure.com
    ftp: connect: Connection timed out
    ftp> 

https://ccl.clozure.com/download.html

> Clozure CL is currently distributed via GitHub. Please refer to [1.12 release page](https://github.com/Clozure/ccl/releases/tag/v1.12) on GitHib. *The old Subversion repository is obsolete.*

**Comment by stew-j** [comment]
^^^^
https://ccl.clozure.com/ftp/pub/release/1.7/

**Comment by stew-j** [comment]
Which as predicted, caused other problems--ASDF is no longer finding the project in CCL 1.7 or 1.8.

    Error: module KONS-9 was not provided by any function on *MODULE-PROVIDER-FUNCTIONS*

the same message in both.

**Comment by mdbergmann** [comment]
You can update ASDF to the latest. So you can then actually also use quicklisp.

Not sure, but maybe this helps:
http://retro-style.software-by-mabe.com/blog/House+automation+tooling+-+Part+1+-+CL+on+MacOSX+Tiger
