### ISSUE TITLE
BUG: shading wrong when window re-opened

### ISSUE THREAD

**Issue by kaveh808** [kaveh808/kons-9#50]
Looking for a volunteer for this.

This is a bug on both MacOS and Linux, so is probably an OpenGL issue.

Open window.
Create polyhedron.
Close window.
Open window.
Shading is much brighter.

I suspect some OpenGL state is not being reset properly.

**Comment by JMC-design** [comment]
Do you mean when you iconify or minimize the window? or after closing it and restarting?

**Comment by kaveh808** [comment]
Closing it using the ESC key. Then making a new window.

**Comment by JMC-design** [comment]
Can confirm it becomes almost white.  Funny thing is, if it crashes then the change in shading doesn't happen.

**Comment by mikelevins** [comment]
Can confirm is happens on Windows 64-bit as well as on macOS and Linux.
