### ISSUE TITLE
Implement basic 2D graphics for GUI

### ISSUE THREAD

**Issue by kaveh808** [kaveh808/kons-9#75]

**Comment by awolven** [comment]
a basic substrate is being created for this, for the purpose of supporting
text, but can be used for any 3d shapes.  more to come.

**Comment by awolven** [comment]
* 2d shapes

**Comment by kaveh808** [comment]
Excellent.

I'm working on 2D code for displaying popup menus. Looking forward to plugging in the text display when it's ready.

I think the main thing I'll need to start with is the ability to display centered text in a rect.

Hope I'm not duplicating what you're doing. I was going to push later today but I can hold off if you prefer.
