### ISSUE TITLE
motion is-active? demo

### ISSUE THREAD

**Issue by JMC-design** [kaveh808/kons-9#83]
When an object becomes inactive and then activated some time later, it will jump to the position it would have been in had it not been inactive.
Is this the desired behaviour, or should an object resume from where it was left off?

**Comment by kaveh808** [comment]
That depends on what the animator is doing. Animators and motions are active, not shapes (objects).

If it is setting a transform based on the frame number or time value, the object will jump.

If it is doing something like a dynamic simulation, then the object may pick up where it left off.
