### ISSUE TITLE
plugin/procedural-polygon fails to compile

### ISSUE THREAD

**Issue by mikelevins** [kaveh808/kons-9#86]
Branch: main
Commit: [7ff3015]
Platform: macOS 12.5.1, SBCL 2.2.6

Steps to reproduce:

1. Start SBCL
2. Load kons-9.asdf
3. (asdf:load-system :kons-9)

Expected result: System loads. Can create demo window.

Actual result: COMPILE-FILE-ERROR while compiling "src/plugins/procedural-polygon"

Compiling the file separately yields:
procedural-polygon.lisp:86:1:
  warning: 
    Duplicate definition for MAKE-CIRCLE found in one file.
    --> DEFUN PROGN 
    ==>
      (EVAL-WHEN (:COMPILE-TOPLEVEL)
        (SB-C:%COMPILER-DEFUN 'KONS-9::MAKE-CIRCLE T NIL NIL))

**Comment by starkaiser** [comment]
On GNU/Linux I am not able to reproduce the bug. The project is loaded fine.

**Comment by mikelevins** [comment]
What version of which distribution are you using, and how did you install freetype?

On Debian Bullseye, the asdf load of cl-freetype2 failed on loading freetype, so I used apt to install libfreetype (apt install libfreetype-dev). The asdf load of cl-freetype2 then succeeds, but when I asdf:load-system of kons-9 I see the same error that I saw on macOS:

COMPILE-FILE-ERROR while compiling
   #<CL-SOURCE-FILE "kons-9" "src/plugins/procedural-polygon">

Once again, compiling just the offending source file yields the same error:

procedural-polygon.lisp:86:1:
  warning: 
    Duplicate definition for MAKE-CIRCLE found in one file.
    --> PROGN DEFUN PROGN 
    ==>
      (EVAL-WHEN (:COMPILE-TOPLEVEL)
        (SB-C:%COMPILER-DEFUN 'KONS-9::MAKE-CIRCLE T NIL NIL))

To account for the possibility of a stale fasl, I deleted my caches sbcl fasls and rebuilt in a fresh session. Same result.

What have you done differently?

**Comment by kaveh808** [comment]
My bad. Will fix and push. Funny I didn't get an error either, but there was a duplicate macro call in the file.

**Comment by mikelevins** [comment]
Interesting. Different defaults in different versions of sbcl, maybe?
