### ISSUE TITLE
Where are the Discussions?

### ISSUE THREAD

**Issue by bigos** [kaveh808/kons-9#91]
The https://github.com/kaveh808/kons-9/blob/main/README.md mentions:

> Read the Introductions thread in Discussions.

Where are the discussion? The link would be very helpful.

**Comment by kaveh808** [comment]
https://github.com/kaveh808/kons-9/discussions

**Comment by bigos** [comment]
https://github.com/bigos/kons-9/blob/main/README.md

like this?
